name: movie_notes
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.3 
  provider: ^6.1.2
  get_it: ^7.7.0 
  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2741.0
  flutter_datetime_picker_plus: ^2.2.0
  google_fonts: ^6.2.1 
  sqflite: ^2.3.3+1
  image_picker: ^1.1.1
  # flutter_riverpod: ^2.5.1
  # riverpod_annotation: ^2.3.5
  intl: ^0.19.0
  searchable_listview: ^2.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # riverpod_lint: ^2.3.10
  # riverpod_generator: ^2.4.0
  auto_route_generator: ^8.0.0
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/2.0x/
    - images/3.0x/

  
